PicnicSupermarket/error-prone-support

.github/workflows/build.yaml, .github/workflows/deploy-website.yaml
In #253 the GHA workflow was edited to use `$default-branch`. Whilst this works in workflow templates, this actually doesn't in a workflow.
Here, we revert to referencing `master` directly.
=> Fix default branch reference in GitHub Actions definition

error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/ExplicitEnumOrdering.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/FormatStringConcatenation.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/Slf4jLogStatement.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/StringJoin.java, error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/StringJoinTest.java
```
Introduce `StringJoin` check (#194)
This new `BugChecker` flags `String#format` invocations which can be
replaced with a `String#join` or even `String#valueOf` invocation.
```
=> Introduce `StringJoin` check

error-prone-contrib/src/main/java/tech/picnic/errorprone/refastertemplates/ReactorTemplates.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refastertemplates/ReactorTemplatesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refastertemplates/ReactorTemplatesTestOutput.java
Add a new refaster template rule that rewrites `.onErrorResume(e -> Mono.empty())` to `.onErrorComplete()`. This is applied to `.onErrorResume(e -> Flux.empty())` as well.
=> Introduce `{Mono,Flux}OnErrorComplete` Refaster rules

error-prone-contrib/src/main/java/tech/picnic/errorprone/refastertemplates/ReactorTemplates.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refastertemplates/ReactorTemplatesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refastertemplates/ReactorTemplatesTestOutput.java
```
Suggest `Flux#concatMap{,Iterable}` usage in more contexts (#279)
```
=> Prefer `flatMapIterable(identity())` over `flatMap(i -> FluxfromIterable(i))`

error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/Slf4jLogStatementTest.java
The test class name is inconsistent with the actual class name. Spotted while generating the documentation website. Decided to split it off given the unforeseeable future of the documentation generation branches. Thought to do it in scope of #288 as we were already renaming files there to make Refaster naming consistent, but this class is unrelated in that regard. 
```
Rename `Slf4JLogStatementTest` to `Slf4jLogStatementTest` (#289)
```
=> Rename `Slf4JLogStatementTest` to `Slf4jLogStatementTest`

README.md
Full output when running in an example project below (with `<showWarnings>true</showWarnings>`)
As one is an `INFO` message and the other a `COMPILATION WARNING` I've cleaned the result up.
```sh
[INFO] /Users/japborst/Documents/dev/error-prone-demo/src/main/java/com/example/Example.java:[9,34] [Refaster Rule] BigDecimalRules.BigDecimalZero: Refactoring opportunity
(see https://error-prone.picnic.tech/refasterrules/BigDecimalRules#BigDecimalZero)
Did you mean 'return BigDecimal.ZERO;'?
[INFO] -------------------------------------------------------------
[WARNING] COMPILATION WARNING :
[INFO] -------------------------------------------------------------
[WARNING] /Users/japborst/Documents/dev/error-prone-demo/src/main/java/com/example/Example.java:[14,35] [IdentityConversion] This method …
```
=> Fix and simplify documented example compiler output

pom.xml
Noticed while testing #309. Suggested commit message:
```
Don't update `project.build.outputTimestamp` on `mvn versions:set` (#310)
As we rely on the value of `git.commit.time` instead.
```
=> Don't update `project.build.outputTimestamp` on `mvn versions:set`

error-prone-contrib/pom.xml, error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/FormatStringConcatenation.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/LexicographicalAnnotationAttributeListing.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/StringJoin.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/package-info.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/util/package-info.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssortedRules.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/MultimapRules.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/NullRules.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/OptionalRules.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/StringRules.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/package-info.java, error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/RequestParamTypeTest.java, pom.xml, refaster-compiler/pom.xml, refaster-compiler/src/main/java/tech/picnic/errorprone/refaster/plugin/RefasterRuleCompilerTaskListener.java, refaster-compiler/src/main/java/tech/picnic/errorprone/refaster/plugin/package-info.java, refaster-runner/pom.xml, refaster-runner/src/main/java/tech/picnic/errorprone/refaster/runner/package-info.java, refaster-support/pom.xml, refaster-support/src/main/java/tech/picnic/errorprone/refaster/annotation/package-info.java, refaster-support/src/main/java/tech/picnic/errorprone/refaster/matchers/package-info.java, refaster-support/src/main/java/tech/picnic/errorprone/refaster/package-info.java, refaster-support/src/test/java/tech/picnic/errorprone/refaster/matchers/AbstractMatcherTestChecker.java, refaster-test-support/pom.xml, refaster-test-support/src/main/java/tech/picnic/errorprone/refaster/test/RefasterRuleCollection.java, refaster-test-support/src/main/java/tech/picnic/errorprone/refaster/test/package-info.java, refaster-test-support/src/test/java/tech/picnic/errorprone/refaster/test/ValidRules.java
:exclamation: This PR is currently on top of #182 :exclamation:
```
Migrate from JSR 305 to JSpecify (#181)
JSpecify's annotations have more well-defined semantics. Its `@Nullable`
annotation is also a type-use annotation recognized by Google Java
Format, so the formatter places it after any field or method modifiers.
See https://jspecify.dev
```
~This is a draft PR. The build currently fails because `LexicographicalAnnotationListing` now incorrectly suggests swapping `@Nullable` and `@Override` annotations.~ #182 resolves this.
=> Migrate from JSR 305 to JSpecify

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
In Reactor versions prior to 3.5.0, `Flux#take(n)` makes an unbounded request upstream, and is equivalent to `Flux#take(n, false)`. In 3.5.0, the behavior of `Flux#take(n)` will change to that of `Flux#take(n, true)`.
The intent with this Refaster rule is to get the new behavior before upgrading to Reactor 3.5.0.
=> Prefer `Flux#take(long, boolean)` over `Flux#take(long)` to limit upstream generation

error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/FluxFlatMapUsage.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/util/MoreTypes.java, error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/FluxFlatMapUsageTest.java
Introduce check for calling flatMap() on Flux<GroupedFlux> or Flux<Flux>
=> Have `FluxFlatMapUsage` better handle nested `Publisher`s

error-prone-contrib/pom.xml, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
These proposed Refaster rules are solely meant to increase the readability when zipping publishers.
In the PR description I'll explain the proposal for `Mono#zipWith()`, but the same applies for the other proposed rules.
---
For example, `Mono#zipWith()` usages make it look like both `Mono`s are not retrieved concurrently, but have a sequential dependency like usages of `Mono#zipWhen()` require.
The following example illustrates the limited readability of `Mono#zipWith()` usages:
```java
Mono<String> zipWithExample(String id) {
return aService.getA(id).zipWith(bService.getB(id), this::combineAsString);
}
```
Reactive publishers should be "streams of data", but in this example it's not apparent that a tuple is created and ultimately mapped to a string.
This PR suggests to rewrite such …
=> Introduce `{Mono,Flux}#zipWith{,Iterable}` Refaster rules

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Based on a suggestion from [here](https://github.com/PicnicSupermarket/picnic-platform/pull/8878#discussion_r851248541).
Adds a Refaster template to prefer `mono.map(x -> valueTransformation(x))` over the `mono.flatMap(x -> Mono.just(valueTransformation(x)))`
This avoids an unnecessary inner inner subscription.
=> Introduce `{Mono,Flux}Map{,NotNull}` Refaster rules

.github/workflows/deploy-website.yaml
```
Improve build and deployment concurrency handling (#284)
Builds for the same branch are now serialized. Among other things this prevents
concurrent deployments.
While there, reduce the permission assigned to each of the two jobs.
```
=> Improve build and deployment concurrency handling

error-prone-contrib/pom.xml, error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/CollectorMutability.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/ScheduledTransactionTrace.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/StaticImport.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/util/ThirdPartyLibrary.java, error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/CollectorMutabilityTest.java, error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/ScheduledTransactionTraceTest.java, error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/util/ThirdPartyLibraryTest.java
As-is, this is especially relevant for users who do not use Guava or the New Relic Agent API, as mentioned [here](https://www.reddit.com/r/java/comments/y2u8tv/comment/is50d1u/?utm_source=share&utm_medium=web2x&context=3). Note that most `BugChecker`s don't need to be modified, since any third-party references in their suggestions must already be present if the check is to trigger at all.
```
By default, prevent `BugChecker`s from introducing new dependencies (#308)
```
We should implement something similar for Refaster, but that will look quite different (and is out of scope for this PR).
=> By default, prevent `BugChecker`s from introducing new dependencies

error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/StringJoin.java
Thanks a lot for providing error-prone-support! I'm using it inside SonarQube and the links to the doc are useful.
The link for the StringJoin bug checker should be https://error-prone.picnic.tech/bugpatterns/StringJoin/
=> Configure documentation URL for `StringJoin` check

README.md
congratulations, your latest releases were proven reproducible
Let's celebrate with this badge :)
=> add Reproducible Builds badge

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/OptionalRules.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/StreamRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/OptionalRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/OptionalRulesTestOutput.java
After I had found this construct during code review.
A mixture of `Optional#map()` and `Optional#filter()` is however not supported with these rules. At this point it seems that Refaster won't be enough, I suspect?
```java
optional.stream().map(x -> x).filter(x -> true).find{Any,First}
```
```
Introduce `OptionalStream{Filter,Map}` Refaster rules (#327)
```
=> Introduce `Optional{Filter,Map}` Refaster rules

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/MapRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/MapRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/MapRulesTestOutput.java
Adds an additional refaster Map rule that builts on https://github.com/PicnicSupermarket/error-prone-support/pull/337
```
Introduce `map.keySet().isEmpty()` to `map.isEmpty()` refaster rule
```
=> Introduce `MapIsEmpty` Refaster rule

.renovaterc.json
As discussed [here](https://github.com/PicnicSupermarket/error-prone-support/pull/345#pullrequestreview-1178125382).
=> Have Renovate file `ruby/setup-ruby` upgrade PRs at most once a month

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
As I had noticed during code review. :+1: 
```
Extend `MonoFlux` Refaster rule (#358)
```
=> Extend `MonoFlux` Refaster rule

error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/AutowiredConstructor.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/EmptyMethod.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/util/SourceCode.java, error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/AutowiredConstructorTest.java, error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/EmptyMethodTest.java, error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/util/SourceCodeTest.java
```
Improve `Tree` deletion suggestions (#347)
When suggesting to remove a method or method annotation, also remove any
trailing whitespace. This avoids the possible introduction of an empty
line right at the start of a code block.
```
See also [this comment](https://github.com/PicnicSupermarket/error-prone-support/pull/198#discussion_r1019570033).
=> Improve `Tree` deletion suggestions

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Saw "good first issue" and could not help myself 😄 
Issue: https://github.com/PicnicSupermarket/error-prone-support/issues/363
Would like some suggestions on the rule names, not too happy with `FluxSwitchIfEmptyOfMonoOrFluxJust` especially.
=> Introduce `{Mono,Flux}DefaultIfEmpty` Refaster rules

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
These proposed Refaster rules primarily aim to make Reactor code more readable as nested `Publisher`s are avoided (e.g. `Mono<Mono<String>>`).
They may result in a minor performance improvement due to the dropped `map()` calls.
I've noticed an occurrence of the following code pattern:
```java
Mono<String> method1() {
Mono.just("foo")
.map(str -> method2(str))
.flatMap(identity());
}
Mono<String> method2(String str) {
...
} 
```
which these changes rewrite to:
```java
Mono<String> method1() {
Mono.just("foo")
.flatMap(str -> method2(str));
}
```
Conceptionally, the same applies for:
- `Mono#flatMap(Function)`
- `Mono#flatMapMap(Function)`
- `Flux#concatMap(Function)`
- `Flux#concatMap(Function, int)`
and in theory also for some others (e.g. `Flux#flatMap()`), but these are already …
=> Introduce some Refaster rules that avoid nested `Publisher`s

error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/util/MoreTypesTest.java, pom.xml
```
Improve mutation testing setup (#383)
- Enable Pitest's built-in `STRONGER` mutator group.
- Enable Arcmutate's `EXTENDED` mutator group.
- Enable Arcmutate's JUnit 5 Accelerator Plugin.
- Modify `MoreTypesTest` such that it is impacted by mutations of the
`MoreTypes` class.
See:
- https://pitest.org/quickstart/mutators/
- https://docs.arcmutate.com/docs/extended-operators.html
- https://docs.arcmutate.com/docs/accelerator.html
```
=> Improve mutation testing setup

.github/workflows/build.yaml, .github/workflows/pitest-analyze-pr.yml, .github/workflows/pitest-update-pr.yml
This reverts commit 5afa7e1878453f97996ed73c36847844e07074cb. The v3.7.0 release got deleted, for context see
https://github.com/actions/setup-java/issues/422.
=> Downgrade actions/setup-java v3.7.0 -> v3.6.0

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
After https://github.com/PicnicSupermarket/error-prone-support/pull/384 I noticed a few more interactions between the Optional and Mono API we can simplify.
Pretty simple cases, but why not cover them?
---
```
Introduce `Mono{Empty,Just,JustOrEmpty}` Refaster rules (#385)
```
=> Introduce `Mono{Empty,Just,JustOrEmpty}` Refaster rules

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
I've spotted the following interesting pattern:
```java
Optional.of(someNullableValue())
.map(Mono::just)
.orElse(someMono());
```
The mix between `Optional` and `Mono` API is unnecessary.
These rules aim to rewrite these to:
```java
Mono.justOrEmpty(someNullableValue())
.switchIfEmpty(someMono());
```
---
```
Introduce `MonoFromOptionalSwitchIfEmpty` Refaster rule (#384)
```
=> Introduce `MonoFromOptionalSwitchIfEmpty` and `OptionalMapMonoJust` Refaster rules

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/CollectionRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/CollectionRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/CollectionRulesTestOutput.java
Related to the issue #387, I added a new Refaster rule to rewrite the use of `forEach` when working with collections.
=> Introduce `CollectionForEach` Refaster rule

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/BigDecimalRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/BigDecimalRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/BigDecimalRulesTestOutput.java
A very nice rule to rewrite `new BigDecimal(long/int)` to `BigDecimal.valueOf(long/int)` already existed. As using `new BigDecimal(double)` is [quite discouraged](https://rules.sonarsource.com/java/RSPEC-2111), this PR extends the existing rule to rewrite `new BigDecimal(double/long/int)` to `BigDecimal.valueOf(double/long/int)`
=> Prefer `BigDecimal.valueOf(double)` over `new BigDecimal(double)`

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ComparatorRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ComparatorRulesTestOutput.java
This is a workaround for google/error-prone#3584.
```
Prevent `ReverseOrder` Refaster rule from introducing a static import (#397)
This is a workaround for the issue resolved by google/error-prone#3584.
After application of this Refaster rule, any static imports of
`java.util.Collections.reverseOrder` are obsolete. These can be removed by
running Google Java Format or Error Prone's `RemoveUnusedImports` check.
Where possible, subsequent application of the `StaticImport` check will
statically import `java.util.Comparator.reverseOrder`.
```
=> Prevent `ReverseOrder` Refaster rule from introducing a static import

.github/ISSUE_TEMPLATE/feature_request.md
(This has no priority but a minor quality of life improvement.)
When creating a ticket it is a bit annoying that the proposed format and code indented. 
One should manually remove this which is not so nice and can be forgotten.
I also noticed others didn't always notice this indentation.
Let me know what you guys think :).
```
Drop indentation in feature request issue template (#403)
While there, add "Improve performance" as a rewrite reason. 
```
=> Drop indentation in feature request issue template

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
We came across this pattern in our code base after some (automatic) refactorings.
```java
mono
.flatMap(operationReturningMonoVoid)
.flux()
.then();
```
`.flux().then()` doesn't add anything, similarly to calling `.then` on a `Mono<Void>`.
Introduced two rules for both steps
---
```
Introduce `MonoFluxThen` and `MonoVoidThen` Refaster rules (#405)
```
=> Introduce `MonoIdentity` and `MonoThen` Refaster rules

pom.xml
```
Upgrade Error Prone fork v2.16-picnic-1 -> v2.16-picnic-2 (#410)
See:
- https://github.com/PicnicSupermarket/error-prone/releases/tag/v2.16-picnic-2
- https://github.com/PicnicSupermarket/error-prone/compare/v2.16-picnic-1...v2.16-picnic-2
```
=> Upgrade Error Prone fork v2.16-picnic-1 -> v2.16-picnic-2

error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/NestedOptionals.java, error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/NestedOptionalsTest.java
While testing version 0.6.0 I encountered a `NullPointerException` thrown by `NestedOptinal` when analysing this code (please don't judge, it's a bug sample!):
```
void m() {
java.time.Duration.of(1, ChronoUnit.YEARS);
}
```
This PR adds a unit test reproducing the problem and a proposed fix.
Thanks a lot for providing this project!
=> Prevent `NestedOptionals` from throwing an NPE

.github/workflows/build.yaml
See the analysis in #418 for context.
```
Disable failing JDK 20-ea build for now (#419)
The build fails due to
openjdk/jdk20@2cb64a75578ccc15a1dfc8c2843aa11d05ca8aa7; the upcoming
Error Prone release includes a workaround for this:
google/error-prone@df033f03cb55c3f26221660ac5ea49bbaeeab289.
```
=> Disable failing JDK 20-ea build for now

error-prone-contrib/pom.xml, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/JUnitToAssertJRules.java, error-prone-contrib/src/test/java/tech/picnic/errorprone/refasterrules/RefasterRulesTest.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/JUnitToAssertJRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/JUnitToAssertJRulesTestOutput.java, pom.xml
Related issue: https://github.com/PicnicSupermarket/error-prone-support/issues/402
Left `XXX` comments on `org.junit.jupiter.api.Assertions` methods that do not (yet) have rules.
Decided to leave the equality-related ones for a follow-up PR to reduce the scope a little bit, as those also need a bit more work (equality with deltas, etc.).
* `assertEquals`
* `assertArrayEquals`
* `assertIterableEquals`
* `assertNotEquals`
The following methods don't seem to have direct AssertJ equivalents, but could also be handled later.
* `assertLinesMatch`
* `assertAll`
* `assertTimeout`
* `assertTimeoutPreemptively`
=> Introduce `JUnitToAssertJRules` Refaster rule collection

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/NullRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/NullRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/NullRulesTestOutput.java
Related issue: #364
Added Rules:
- prefer `requireNonNullElse(A, B)` over `Optional.ofNullable(A).orElse(B)`
- prefer `requireNonNullElseGet(A, () -> B)` over `Optional.ofNullable(A).orElseGet(() -> B)`
Wrote test inputs and outputs.
**Potential problems:**
In the tests, referenced `Optional` by it's fully qualified name to avoid breaking `RefasterRulesTest` or leaving unused imports in the code. - this seems hacky but didn't came up with better solution.
Neither the new or already existing rules are not dealing with potential NPE when the second argument can be or produce null. - this seems to be a larger or at least a separated issue.
=> Introduce/extend `RequireNonNullElse{,Get}` Refaster rules

.github/workflows/build.yaml, pom.xml
Not sure why Renovate didn't open a PR (and didn't investigate), but here it is.
```
Upgrade Error Prone 2.16 -> 2.17.0 (#432)
See:
- https://github.com/google/error-prone/releases/tag/v2.17.0
- https://github.com/google/error-prone/compare/v2.16...v2.17.0
- https://github.com/PicnicSupermarket/error-prone/compare/v2.16-picnic-2...v2.17.0-picnic-1
```
=> Upgrade Error Prone 2.16 -> 2.17.0

error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/LexicographicalAnnotationAttributeListing.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/RedundantStringConversion.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/RequestParamType.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/util/Flags.java, error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/RequestParamTypeTest.java, error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/util/FlagsTest.java
One would want to use classes such as `ImmutableList` with `@RequestParam` given that the custom support for the underlying conversion is provided. For such occasions we can specify the classes we wish to be included on top of what is already provided (by Spring) by using the flag `-XepOpt:RequestParamType:Includes=<class-name>`
=> Have `RequestParamType` ignore parameter types with custom deserialization support

apply-error-prone-suggestions.sh, run-mutation-tests.sh
```
Have `apply-error-prone-suggestions.sh` download JitPack-hosted artifacts (#441)
While there, tweak the usage message of both `apply-error-prone-suggestions.sh`
and `run-mutation-tests.sh`.
```
=> Have `apply-error-prone-suggestions.sh` download JitPack-hosted artifacts

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/MapRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/MapRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/MapRulesTestOutput.java
adds rules to fix #431.
Added Rules:
-  prefer `map.getOrDefault(k, defaultValue)` over `requireNonNullElse(map.get(k), defaultValue)`
Wrote test inputs and outputs.
Could be a problem that when `defaultValue` is null, `Objects#requireNonNullElse` throws a NPE while `Map#getOrDefault` does not.
=> Introduce `MapGetOrDefault` Refaster rule

pom.xml, refaster-runner/src/main/java/tech/picnic/errorprone/refaster/runner/Refaster.java, refaster-support/src/main/java/tech/picnic/errorprone/refaster/AnnotatedCompositeCodeTransformer.java, refaster-support/src/test/java/tech/picnic/errorprone/refaster/AnnotatedCompositeCodeTransformerTest.java, refaster-support/src/test/java/tech/picnic/errorprone/refaster/matchers/AbstractMatcherTestChecker.java
```
Upgrade Error Prone 2.17.0 -> 2.18.0 (#455)
See:
- https://github.com/google/error-prone/releases/tag/v2.18.0
- https://github.com/google/error-prone/compare/v2.17.0...v2.18.0
- https://github.com/PicnicSupermarket/error-prone/compare/v2.17.0-picnic-1...v2.18.0-picnic-1
```
=> Upgrade Error Prone 2.17.0 -> 2.18.0

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
After applying EPS on a repository, I've noticed essentially the following interesting pattern:
```java
Mono.<Void>empty().flux().next()
```
- `Mono#flux()` converts the `Mono` to a `Flux` as-is.
- `Flux#next()` however simply takes the first element in the `Flux` or returns empty without any side-effects (contrary to `Flux#single()`).
So, this is practically a no-op.
```
Extend `MonoIdentity` Refaster rule (#465)
By flagging expressions of the form `mono.flux().next()`.
```
=> Extend `MonoIdentity` Refaster rule

error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/PrimitiveComparisonTest.java, pom.xml
```
Enable Checkstyle's `JavadocStyle` module (#451)
See: 
- https://checkstyle.org/config_javadoc.html#JavadocStyle
- https://checkstyle.org/apidocs/com/puppycrawl/tools/checkstyle/checks/javadoc/JavadocStyleCheck.html
```
=> Enable Checkstyle's `JavadocStyle` module

pom.xml
```
Enable additional `maven-enforcer-plugin` rules (#489)
```
=> Enable additional `maven-enforcer-plugin` rules

README.md
I have been using `error-prone-support` in a [personal toy project](https://github.com/ghokun/convert) and realized that there is no installation instruction for `gradle` in website. This PR adds that.
=> Add Gradle installation instructions to README

pom.xml
```
Upgrade Maven API 3.8.6 -> 3.8.7 (#498)
See:
- https://maven.apache.org/docs/3.8.7/release-notes.html
- https://github.com/apache/maven/releases/tag/maven-3.8.7
- https://github.com/apache/maven/compare/maven-3.8.6...maven-3.8.7
```
=> Upgrade Maven API 3.8.6 -> 3.8.7

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
```
Introduce `FluxCount` Refaster rules (#516)
```
=> Introduce `FluxCountMapMathToIntExact` Refaster rule

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ImmutableMapRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ImmutableMapRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ImmutableMapRulesTestOutput.java
Hesitated for a sec to also cover `FilterEntries`, but I reckon this has less usages and will somehow conflict with `FilterValues` and `FilterKeys`, so I left it out. 
```
Introduce `ImmutableMapFilter{Keys,Values}` Refaster rules (#517)
```
=> Introduce `ImmutableMapCopyOfMapsFilter{Keys,Values}` Refaster rules

.github/ISSUE_TEMPLATE/bug_report.md, .github/workflows/build.yaml, .github/workflows/pitest-analyze-pr.yml, .github/workflows/pitest-update-pr.yml, error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/util/SourceCodeTest.java, pom.xml
```
Upgrade JDKs used by GitHub Actions builds (#521)
Additionally:
- Update the example version numbers mentioned in the issue template.
- Drop some redundant whitespace from `SourceCodeTest` test code.
- Sort some compiler arguments.
See:
- https://www.oracle.com/java/technologies/javase/11-0-17-relnotes.html
- https://www.oracle.com/java/technologies/javase/11-0-18-relnotes.html
- https://www.oracle.com/java/technologies/javase/17-0-5-relnotes.html
- https://www.oracle.com/java/technologies/javase/17-0-6-relnotes.html
- https://www.oracle.com/java/technologies/javase/19-0-1-relnotes.html
- https://www.oracle.com/java/technologies/javase/19-0-2-relnotes.html
```
=> Upgrade JDKs used by GitHub Actions builds

documentation-support/src/test/java/tech/picnic/errorprone/documentation/BugPatternExtractorTest.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssertJStringRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJStringRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJStringRulesTestOutput.java
Identified while reviewing #494.
```
Introduce `AssertThatPathContent{,Utf8}` Refaster rules (#530)
```
=> Introduce `AssertThatPathContent{,Utf8}` Refaster rules

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Following [this suggestion](https://github.com/PicnicSupermarket/picnic-platform/pull/9982#discussion_r1133960563).
```
Drop usage of redundant `expectNextCount(0)` checks
```
=> Extend `StepVerifierStepIdentity` Refaster rule

error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/util/MoreASTHelpers.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/NullRules.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/PreconditionsRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/NullRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/NullRulesTestOutput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/PreconditionsRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/PreconditionsRulesTestOutput.java
Follow up of this [issue](https://github.com/PicnicSupermarket/error-prone-support/issues/437).
```
Extend `null` check Refaster rules (#523)
- Replace `CheckNotNull` with `RequireNonNull{,WithMessage}{,Statement}`.
- Extend `Is{,Not}Null`.
Fixes #437.
```
=> Extend `null` check Refaster rules

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Following [this suggestion](https://github.com/PicnicSupermarket/picnic-store/pull/2403#discussion_r1155845343).
```
Introduce `MonoJustOrEmptyOptional` Refaster rule (#563)
While there, rename two other rules.
```
=> Introduce `MonoJustOrEmptyOptional` Refaster rule

error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/util/SourceCode.java, error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/util/SourceCodeTest.java
```
Introduce `SourceCode#unwrapMethodInvocation` utility method (#561)
```
I'll rebase #560 on top of this PR to use the new method. Another upcoming PR will also use it.
=> Introduce `SourceCode#unwrapMethodInvocation` utility method

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Idea is based on an internal GH thread.
```
Introduce `FluxCollectToImmutableSet` Refaster rule (#571)
```
=> Introduce `FluxCollectToImmutableSet` Refaster rule

error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/IdentityConversion.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Based on internal inquiry
```
Introduce `FluxCollectToImmutableList` Refaster rule (#570)
```
=> Introduce `FluxCollectToImmutableList` Refaster rule

CONTRIBUTING.md, README.md, SECURITY.md, run-full-build.sh
```
Improve contribution documentation (#572)
- Introduce a `./run-full-build.sh` script.
- Explicitly mention that users should run this script before opening a pull
request.
- Emphasize that many build warnings can be resolved automatically.
- Introduce a `SECURITY.md` file as suggested by GitHub.
```
Context of this PR: I've registered Error Prone Support with the [OpenSSF Best Practices Badge Program](https://bestpractices.coreinfrastructure.org/en/projects/7199), and these changes increase our compliance. (Other PRs to improve compliance may follow.)
=> Improve contribution documentation

error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/RedundantStringConversionTest.java, error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/util/JavaKeywordsTest.java, error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/util/MethodMatcherFactoryTest.java, error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/util/ThirdPartyLibraryTest.java
```
Apply assorted test cleanup (#562)
- Inline more `CompilationTestHelper` fields.
- Move inner class to the bottom of the outer class.
- Improve test parameter name.
```
=> Apply assorted test cleanup

error-prone-contrib/src/test/java/tech/picnic/errorprone/refasterrules/RefasterRulesTest.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/SuggestedFixRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/SuggestedFixRulesTestOutput.java
Yeah... (noticed while rebasing the `website` branch: it's build [fails](https://github.com/PicnicSupermarket/error-prone-support/actions/runs/4688569656/jobs/8309237519) on the unknown `Suggestions` type.
```
Fix and enable `SuggestedFixRules` tests (#581)
```
=> Fix and enable `SuggestedFixRules` tests

.github/workflows/build.yaml, .github/workflows/deploy-website.yaml, .github/workflows/openssf-scorecard.yml, .github/workflows/pitest-analyze-pr.yml, .github/workflows/pitest-update-pr.yml
```
Introduce OpenSSF Scorecard GitHub action (#574)
And resolve some of the issues it identified.
See https://securityscorecards.dev
```
For the output, see [this view](https://github.com/PicnicSupermarket/error-prone-support/security/code-scanning?query=is%3Aopen+pr%3A574). Only warnings about non-pinned dependencies remain. Those can be resolved using [Renovate](https://docs.renovatebot.com/modules/manager/github-actions/#additional-information), IIUC, so I propose we address that separately.
=> Introduce OpenSSF Scorecard GitHub action

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssertJMapRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJMapRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJMapRulesTestOutput.java
Original suggestion [here](https://github.com/PicnicSupermarket/picnic-platform/pull/10073#discussion_r1155822141).
```
Introduce `AssertThatMapContainsOnlyKeys` Refaster rule (#576)
```
=> Introduce `AssertThatMapContainsOnlyKeys` Refaster rule

error-prone-contrib/README.md, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/StringRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StringRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StringRulesTestOutput.java
Original suggestion [here](https://github.com/PicnicSupermarket/picnic-platform/pull/10073#discussion_r1156033284).
```
Prefer `not(String::isEmpty) over `s -> !s.isEmpty()` for Predicates
```
=> Introduce `StringIs{,Not}EmptyPredicate` Refaster rules

error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/AssociativeMethodInvocation.java, error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/AssociativeMethodInvocationTest.java
~:exclamation: This PR is on top of #561. :exclamation:~
```
Introduce `AssociativeMethodInvocation` check (#560)
```
This is in preparation for a bug checker that collapses multiple `@BeforeTemplate` methods into a single `Refaster.anyOf` method; such code changes may require flatting of nested `Refaster.anyOf` expressions; something taken care of by this check.
=> Introduce `AssociativeMethodInvocation` check

README.md
```
Add additional quality badges to README (#584)
```
Check [this link](https://github.com/PicnicSupermarket/error-prone-support/tree/sschroevers/more-badges) to see what it would look like on the home page. I considered other orders/formatting, but none looked obviously better. Let's merge #575 before we merge this PR.
W.r.t. whether to show multiple SonarCloud badges: I opted for "yes", as it does concisely summarize the various dimensions along which we achieved high quality.
=> Add additional quality badges to README

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/StreamRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StreamRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StreamRulesTestOutput.java
https://github.com/PicnicSupermarket/error-prone-support/issues/578
* Replace redundant `stream#collect` calls.
[Suggested commit message:](https://github.com/PicnicSupermarket/error-prone-support/pull/593#pullrequestreview-1397175353)
```
Extend `StreamRules` Refaster rule collection (#593)
All changes suggested by SonarCloud's java:S4266 rule are now covered.
See https://sonarcloud.io/organizations/picnic-technologies/rules?open=java%3AS4266&rule_key=java%3AS4266
Fixes #578.
```
1. `stream.collect(minBy(comparator))` -> `stream.min(comparator)`
2. `stream.collect(maxBy(comparator))` -> `stream.max(comparator)`
3. `stream.collect(summingInt(mapper))` -> `stream.mapToInt(mapper).sum()`
4. `stream.collect(summingDouble(mapper))` -> `stream.mapToDouble(mapper).sum()`
5. …
=> Extend `StreamRules` Refaster rule collection

README.md
```
Fix Gradle installation guide link in README (#606)
```
Without this the rendering is [incorrect](https://github.com/PicnicSupermarket/error-prone-support#gradle). Wrapped after 79 chars as usual.
=> Fix Gradle installation guide link in README

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssertJThrowingCallableRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJThrowingCallableRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJThrowingCallableRulesTestOutput.java
While applying the Refaster rules internally I found another case that we are missing. This was intended as this list is not meant to be exhaustive. However, I feel it makes sense to be consistent and for that reason I added some of the missing cases for the `assertThatNullPointerException`, `assertThatIOException`, and `assertThatExceptionOfType`. 
Now we have a `StartsWith`, `MessageContaining`, and `MessageNotContaining` for the ones that already had `WithParams` :smile:.
```
Extend `AssertJThrowingCallableRules` Refaster rule collection (#609)
```
=> Extend `AssertJThrowingCallableRules` Refaster rule collection

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/PrimitiveRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/PrimitiveRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/PrimitiveRulesTestOutput.java
```
Extend `PrimitiveRules` Refaster rule collection (#608)
Assorted methods and constants exposed by Guava's
`com.google.common.primitives.*` types are now replaced with their JDK
equivalents.
While there, also update the parameter types of some existing `@AfterTemplate`
methods, resolving an inconsistency flagged by @knutwannheden.
```
=> Extend `PrimitiveRules` Refaster rule collection

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ImmutableSetRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ImmutableSetRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ImmutableSetRulesTestOutput.java
~~Original discussion.~~
```
Introduce `Sets{Difference,Intersection}{,Map,Multimap}` and `SetsUnion` Refaster rules (#607)
```
=> Prefer Sets#intersection over more contrived alternatives.

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/StreamRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StreamRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StreamRulesTestOutput.java
~:exclamation: This PR is on top of #623. :exclamation:~
Small one that came up recently 🙃 
```
Introduce `StreamsConcat` Refaster rule (#619)
```
=> Introduce `StreamsConcat` Refaster rule

error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/util/ThirdPartyLibrary.java
```
Make `ThirdPartyLibrary` compatible with `-source 8` (#627)
When targeting Java 8, `unnamedModule` is not properly initialized,
causing an NPE when trying to load a class from it. In that context
`noModule` should be used instead.
Fixes #626.
```
=> Make `ThirdPartyLibrary` compatible with `-source 8`

refaster-support/src/test/java/tech/picnic/errorprone/refaster/matchers/AbstractMatcherTestChecker.java
I extracted these changes from [this branch](https://github.com/PicnicSupermarket/error-prone-support/compare/sschroevers/introduce-IsNullableMatcher), following the discussion in [this thread](https://github.com/PicnicSupermarket/error-prone-support/pull/527#discussion_r1173558090). There are no tests for this test code. My proposal would be to finalize #527 on top of this PR as proof that it works. (Over time we'll introduce other `Matcher`s that will rely on (and thus exercise) this code. IIRC I have one or more other branches that would benefit from these changes. I might try to open PRs for those.)
```
Improve `AbstractMatcherTestChecker` (#599)
These changes enable testing of a wider range of `Matcher` implementations. In
a nutshell:
- The `Matcher` under …
```
=> Improve `AbstractMatcherTestChecker`

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Identified as part of the ongoing internal migration to `WebClient`.
=> Introduce `MonoSingle` Refaster rule

pom.xml
```
Upgrade Error Prone fork v2.20.0-picnic-1 -> v2.20.0-picnic-2 (#725)
This new release is a workaround for jitpack/jitpack.io#5741.
See https://github.com/PicnicSupermarket/error-prone/compare/v2.20.0-picnic-1...v2.20.0-picnic-2
```
=> Upgrade Error Prone fork v2.20.0-picnic-1 -> v2.20.0-picnic-2

error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/CanonicalAnnotationSyntax.java
Had these on my list and wanted to fix it.
=> Fix typos in `CanonicalSyntaxAnnotation.java`

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/DoubleStreamRules.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/IntStreamRules.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/LongStreamRules.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/StreamRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/DoubleStreamRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/DoubleStreamRulesTestOutput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/IntStreamRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/IntStreamRulesTestOutput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/LongStreamRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/LongStreamRulesTestOutput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StreamRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StreamRulesTestOutput.java
* Refaster redundant `.filter()` operator in a `Flux` or a `Stream` after using the same predicate in `takeWhile` operator; Since the `takeWhile` short-circuits the stream once predicate is false.
```
Introduce `StreamsTakeWhileFilter` & `FluxTakeWhileFilter` refaster rules (#727)
```
=> StreamsTakeWhileFilter & FluxTakeWhileFilter

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
When verifying a `Flux` only has one element, avoid collecting to list.
Notes:
1. The `@BeforeTemplate` is quite big, can it be a problem? I don't know if/how it can be reduced in size;
2. I am pretty sure the name of the rule is not the best, please suggest one that follows existing standards if you have better ideas;
3. It could be extended to `toImmutableSet` as well (see comment)
4. I used `flux.collect(toImmutableList())` instead of `flux.collectList()` because of the rule `FluxCollectToImmutableList`; 
5. How does it work if there is a match for this rule, but with `flux.collectList()`? Will error-prone perform "two passes" and first move `flux.collectList()` to `flux.collect(toImmutableList())` and then apply my rule?
=> Introduce `VerifyOnlyElementInFlux` Refaster rule

.renovaterc.json
As discussed [here](https://github.com/PicnicSupermarket/error-prone-support/pull/722#issuecomment-1649187860).
=> Have Renovate file GitHub CodeQL upgrade PRs once every four weeks

CONTRIBUTING.md, README.md, run-branch-mutation-tests.sh, run-mutation-tests.sh
```
Introduce mutation test script for changed code (#757)
While there, optimize the existing `run-mutation-tests.sh` script.
```
=> Introduce mutation test script for changed code

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/StreamRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StreamRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StreamRulesTestOutput.java
```
Introduce `StreamIterate` Refaster rule (#762)
```
=> Introduce `StreamIterate` Refaster rule

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/FileRules.java, error-prone-contrib/src/test/java/tech/picnic/errorprone/refasterrules/RefasterRulesTest.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/FileRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/FileRulesTestOutput.java
```
Introduce `FileRules` Refaster rule collection (#767)
```
=> Introduce `FileRules` Refaster rule collection

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/OptionalRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/OptionalRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/OptionalRulesTestOutput.java
```
Introduce assorted `Optional` Refaster rules (#764)
While there, move the `OptionalOrElseGet` Refaster rule test code to the
correct location.
```
=> Introduce assorted `Optional` Refaster rules

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/EqualityRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/EqualityRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/EqualityRulesTestOutput.java
```
Introduce additional equality Refaster rules (#765)
```
=> Introduce additional equality Refaster rules

pom.xml
```
Disallow `autovalue.shaded.*` imports (#774)
```
=> Disallow `autovalue.shaded.*` imports

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Flushing a bunch of changes I had collected locally. This _could_ be split into multiple PRs. Let me know if anybody feels strongly enough about that.
Suggested commit messages:
```
Introduce assorted Reactor Refaster rules (#763)
```
=> Introduce assorted Reactor Refaster rules

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Added `verifyErrorMatches(clazz::isInstance)` as a variant of `verifyErrorSatisfies(t -> assertThat(t).isInstanceOf(clazz))` that we already rewrite.
=> Add another variant to the `StepVerifierLastStepVerifyErrorClass`

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ClassRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ClassRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ClassRulesTestOutput.java
Proposal based on [this comment](https://github.com/PicnicSupermarket/error-prone-support/pull/810#discussion_r1346203628).
```
Introduce `ClassRules` Refaster rule collection (#811)
```
=> Introduce `ClassRules` Refaster rule collection

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/MockitoRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/MockitoRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/MockitoRulesTestOutput.java
```
Introduce additional Mockito Refaster rules (#777)
```
=> Introduce additional Mockito Refaster rules

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
This is mainly intended to prevent `Flux.just()`, preferring the more expressive `Flux.empty()`, but while there why not prevent the other `vararg` constructors from being used without arguments 🤷🏻‍♂️
=> Introduce `FluxEmpty` Refaster rule

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Since semantically this should be equivalent.
```
Introduce `{Mono,Flux}OfType` Refaster rules (#810)
```
=> Introduce `{Mono,Flux}OfType` Refaster rules

error-prone-contrib/src/test/java/tech/picnic/errorprone/refasterrules/RefasterRulesTest.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ClassRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ClassRulesTestOutput.java
Based on something @benhalasi flagged in a different PR: https://github.com/PicnicSupermarket/error-prone-support/pull/771#discussion_r1349739495. 
Struggling with finding the best label for this PR, suggestions?
=> Enable test for `ClassRules` rule collection

error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/StaticImport.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/PatternRules.java, error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/AmbiguousJsonCreatorTest.java, error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/FluxImplicitBlockTest.java, error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/StringJoinTest.java, error-prone-contrib/src/test/java/tech/picnic/errorprone/refasterrules/RefasterRulesTest.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/PatternRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/PatternRulesTestOutput.java, refaster-runner/src/test/java/tech/picnic/errorprone/refaster/runner/RefasterTest.java
```
Introduce `PatternRules` Refaster rule collection (#771)
While there, configure `StaticImport` to not require static importing of
`com.google.common.base.Predicates.contains`.
The new rules triggered cleanup of some `CompilationTestHelper` usages.
See google/guava#6483.
```
=> Introduce `PatternRules` Refaster rule collection

.github/workflows/build.yaml
```
Build and test against JDK 21 instead of JDK 20 (#832)
See https://jdk.java.net/21/release-notes
```
=> Build and test against JDK 21 instead of JDK 20

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/BigDecimalRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/BigDecimalRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/BigDecimalRulesTestOutput.java
Expands the `BigDecimalRules`, mainly preventing contrived uses of `compareTo(BigDecimal.ZERO)` by using `signum()` instead. 
Also adds some rules surrounding the use of `signum()`.
=> Introduce assorted `BigDecimal#signum` Refaster rules

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/PrimitiveRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/PrimitiveRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/PrimitiveRulesTestOutput.java
```
Introduce `{Integer,Long}SignumIs{Positive,Negative}` Refaster rules (#822)
```
These suggestions follow from the discussion in #812.
=> Introduce `{Integer,Long}SignumIs{Positive,Negative}` Refaster rules

error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/NonStaticImport.java, refaster-test-support/src/main/java/tech/picnic/errorprone/refaster/test/RefasterRuleCollection.java
I remembered we wanted to fix this one some time ago.
However, it does a non 100% optimal fix for this specific case as it rewrites it to:
```
BugCheckerRefactoringTestHelper.TestMode.TEXT_MATCH
```
Which can be easily fixed by removing the qualifier, but I'd say flagging this is an improvement for now.
Didn't add a test as we already extensively test the members in the `identification` test.
```
Disallow static import of `BugCheckerRefasctoringTestHelper.TestMode#TEXT_MATCH` (#862)
```
=> Disallow static import of `BugCheckerRefasctoringTestHelper.TestMode#TEXT_MATCH`

refaster-support/src/test/java/tech/picnic/errorprone/refaster/matchers/AbstractMatcherTestChecker.java
```
Simplify `AbstractMatcherTestChecker` (#853)
By using `TreePathScanner` rather than directly using `TreeScanner`.
```
=> Simplify `AbstractMatcherTestChecker`

.github/workflows/sonarcloud.yml
This issue was observed in the context of #925. I added a commit there to validate that the new condition indeed skips the check. For _this_ PR the SonarCloud analysis _should_ run :eyes: :crossed_fingers:
```
Skip SonarCloud analysis of PRs from forked repositories (#926)
Because such analysis will fail due to unavailability of the relevant
secrets. Working around this is nontrivial and a likely source of
security issues.
```
=> Skip SonarCloud analysis of PRs from forked repositories

error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/CanonicalClassNameUsage.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/DirectReturn.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/ExplicitEnumOrdering.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/FluxFlatMapUsage.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/FluxImplicitBlock.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/FormatStringConcatenation.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/IdentityConversion.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/JUnitValueSource.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/MockitoMockClassReference.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/NonEmptyMono.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/PrimitiveComparison.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/RedundantStringConversion.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/RefasterAnyOfUsage.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/StringJoin.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/TimeZoneUsage.java, error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/CanonicalClassNameUsageTest.java, error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/util/MoreMatchersTest.java, refaster-support/src/main/java/tech/picnic/errorprone/refaster/matchers/IsEmpty.java, refaster-support/src/main/java/tech/picnic/errorprone/refaster/matchers/IsIdentityOperation.java, refaster-support/src/main/java/tech/picnic/errorprone/refaster/matchers/IsRefasterAsVarargs.java
```
Introduce `CanonicalClassNameUsage` check (#881)
Error Prone checks deal with source code and type matchers, both of
which generally involve canonical type names, rather than the strings
produced by `Class#getName()`. This distinction is particularly relevant
when dealing with nested types.
```
=> Introduce `CanonicalClassNameUsage` check

error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/NonStaticImport.java
Saw this during a code review 😄.
Probably we can add more from Error Prone later. I checked some other classes from Error Prone but these are clear improvements that we also have been discussing before. Therefore, I decided to start with these two.
=> Disallow static import of `com.google.errorprone.{VisitorState,util.ASTHelpers}` members

pom.xml
See https://github.com/PicnicSupermarket/error-prone-support/pull/925#issuecomment-1861178378: `-XepExcludedPaths:\Q${project.build.directory}${file.separator}\E.*` doesn't work because Error Prone [matches](https://github.com/google/error-prone/blob/21c190a6fc76f3ad3c895639dc66b7a3f570c55d/check_api/src/main/java/com/google/errorprone/ErrorProneAnalyzer.java#L192-L197) against a path that's [derived](https://github.com/google/error-prone/blob/21c190a6fc76f3ad3c895639dc66b7a3f570c55d/check_api/src/main/java/com/google/errorprone/util/ASTHelpers.java#L1552-L1586) from a file's URI, which in practice will always contain forward slashes.
```
Update Error Prone `-XepExcludedPaths` flag to be Windows-compatible (#927)
Prior to these changes the provided pattern would …
```
=> Update Error Prone `-XepExcludedPaths` flag to be Windows-compatible

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/JUnitToAssertJRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/JUnitToAssertJRulesTestOutput.java
This resolves an issue observed internally.
```
Prevent likely static import class with `FailWithMessage{,AndThrowable}` Refaster rules (#939)
This is a workaround for google/error-prone#3584. While there, drop an
unused method from `JUnitToAssertJRules`.
```
(It'd be better to fix google/error-prone#3584, but that looks to be (very) complicated; no time for that right now.)
=> Prevent likely static import class with `FailWithMessage{,AndThrowable}` Refaster rules

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/OptionalRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/OptionalRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/OptionalRulesTestOutput.java
As I spotted this no-op.
```
Extend `OptionalIdentity` Refaster rule (#951)
By flagging expressions of the form `optional.or(() -> Optional.empty())` and 
`optional.or(Optional::empty)`.
```
=> Extend `OptionalIdentity` Refaster rule

error-prone-contrib/pom.xml, pom.xml, refaster-runner/pom.xml, refaster-test-support/pom.xml
See https://github.com/PicnicSupermarket/error-prone-support/pull/925#issuecomment-1873305005 and https://github.com/PicnicSupermarket/error-prone-support/pull/775#issuecomment-1884329098 for context. It turns out that since #515 our IDEA setup is broken due to [IDEA-342187](https://youtrack.jetbrains.com/issue/IDEA-342187). With these changes we can once again run all tests in IDEA. 
```
Work around IntelliJ IDEA bug IDEA-342187 (#958)
This reverts some of the changes in
3578a8cbec7c2d85f20ca8093e257440790d0953.
See https://youtrack.jetbrains.com/issue/IDEA-342187
```
=> Work around IntelliJ IDEA bug IDEA-342187

.github/workflows/build.yml, .github/workflows/codeql.yml, .github/workflows/pitest-analyze-pr.yml, .github/workflows/pitest-update-pr.yml, .github/workflows/run-integration-tests.yml, .github/workflows/sonarcloud.yml
This should unblock PRs #434 and #491.
```
Build with Maven 3.9.6 (#964)
Using the `setup-maven-action` GitHub action we can both simplify the
build configuration and configure the version of Maven to use.
See https://github.com/s4u/setup-maven-action
```
=> Build with Maven 3.9.6

documentation-support/pom.xml, error-prone-contrib/pom.xml, pom.xml, refaster-compiler/pom.xml, refaster-runner/pom.xml, refaster-support/pom.xml, refaster-test-support/pom.xml
```
Run `org.kordamp.maven:pomchecker-maven-plugin:1.10.0:check-maven-central` (#491)
This new Maven goal validates that the `pom.xml` files meet the criteria
for being deployed to Maven Central. 
```
=> Run `org.kordamp.maven:pomchecker-maven-plugin:1.10.0:check-maven-central`

refaster-runner/src/main/java/tech/picnic/errorprone/refaster/runner/Refaster.java
```
Drop workaround for resolved Refaster bug (#974)
Issue google/error-prone#2456 was fixed in Error Prone 2.22.0.
```
=> Drop workaround for resolved Refaster bug

documentation-support/pom.xml, error-prone-contrib/pom.xml, refaster-runner/pom.xml, refaster-support/pom.xml, refaster-test-support/pom.xml
```
Drop unnecessary dependency declarations (#973)
```
=> Drop unnecessary dependency declarations

documentation-support/pom.xml, error-prone-contrib/pom.xml, refaster-runner/pom.xml, refaster-support/pom.xml, refaster-test-support/pom.xml
See https://github.com/PicnicSupermarket/error-prone-support/pull/972#issuecomment-1890770483 and pitest/pitest-junit5-plugin#105. This largely reverts #973.
I'll rebase #972 on top of this PR to prove that this fixes things, but one can also run `./run-mutation-tests.sh` locally to do the same.
```
Fix the mutation test setup (#976)
This largely reverts commit dff67fecbceccde17c4839e37c73dc66a9c65c0f,
avoiding the issue described in pitest/pitest-junit5-plugin#105.
```
=> Fix the mutation test setup

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/MultimapRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/MultimapRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/MultimapRulesTestOutput.java
Suggested commit messages:
```
Introduce additional `Multimap` Refaster rules (#971)
```
=> Introduce additional `Multimap` Refaster rules

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ComparatorRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ComparatorRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ComparatorRulesTestOutput.java
```
Introduce `{Max,Min}ByNaturalOrder` Refaster rules (#970)
```
=> Introduce `{Max,Min}ByNaturalOrder` Refaster rules

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
```
Introduce additional Reactor Refaster rules (#969)
In various contexts, suggest more efficient and/or less verbose
constructs.
```
=> Introduce additional Reactor Refaster rules

pom.xml
Extracted from #603.
```
Actually skip test failures during SonarCloud analysis (#986)
```
To test, run:
```sh
vimdiff \
<(mvn help:effective-pom) \
<(mvn help:effective-pom -Dsonar.projectKey=PicnicSupermarket_error-prone-support)
```
=> Actually skip test failures during SonarCloud analysis

error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/ExplicitEnumOrdering.java, error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/ExplicitEnumOrderingTest.java
```
Prevent `ExplicitEnumOrdering` from throwing an NPE (#998)
```
Found while evaluating Qodana.
=> Prevent `ExplicitEnumOrdering` from throwing an NPE

error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/NonStaticImport.java, error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/NonStaticImportTest.java
We think that in the contexts where this happen it usually _does_ make sense to statically import these identifiers.
=> Allow static imports of `{ZERO,ONE}` identifiers

error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/util/ThirdPartyLibrary.java, error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/ErrorProneRuntimeClasspathTest.java, error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/util/ThirdPartyLibraryTest.java
~:exclamation: This PR is on top of #976. :exclamation:~
```
Have `ErrorProneRuntimeClasspath` ignore non-public types (#972)
```
=> Have `ErrorProneRuntimeClasspath` ignore non-public types

.github/workflows/build.yml
```
Run builds on macOS 14 rather than macOS 12 (#1011)
See https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
```
=> Run builds on macOS 14 rather than macOS 12

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/TimeRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/TimeRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/TimeRulesTestOutput.java
Uses e.g. `LocalDate#plusDays` instead of more contrived alternatives.
Quite a big PR as sadly none of the involved classes share a common interface for the shorthand methods.
=> Use `plus###` and `minus###` shorthands when possible for dates/times

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/StreamRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StreamRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StreamRulesTestOutput.java
Introduces Refaster rule(s) that avoid unnecessary collections when checking whether a stream is empty.
Quick peek at the extension introduced:
`stream.collect(collectingAndThen(collector, Collection::isEmpty));` ➡️ `stream.findAny().isEmpty();`
1. ✅ see https://github.com/PicnicSupermarket/error-prone-support/pull/1025#discussion_r1485240560 ~~Tests currently are not passing because of the errors in Snippet 3 (import statements are different in `StreamRulesTestOutput` wrt. the ones in `StreamRulesTestInput`). If I add them manually, the tests pass but then the build fails because the imports are unused. Once I format, the tests fail again for the same reason. This never happened to me previously~~ 
2. ✅ thank you @Stephan202! Looks much cleaner now ~~I could not find a way to group the …
=> Extend `StreamIsEmpty` Refaster rule

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/StringRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StringRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StringRulesTestOutput.java
fixes: https://github.com/PicnicSupermarket/error-prone-support/issues/1001
=> Introduce `NewStringFromCharArray{,SubSequence}` Refaster rules

.github/workflows/sonarcloud.yml
SonarCloud reports that the `master` branch was [last analyzed](https://sonarcloud.io/summary/new_code?id=PicnicSupermarket_error-prone-support) for revision 7c2078b771f218269534f4c34966e170049d53d8, i.e. just before #926. I noticed that something was off when all new PRs started to report the issue resolved by #1023. The current fix is based on [this SO answer](https://stackoverflow.com/a/66206183).
```
Re-enable SonarCloud analysis on default branch (#1029)
This analysis was accidentally disabled by
ff3be8ae3fc23072976c601e73a2b46d0792d7e9.
```
=> Re-enable SonarCloud analysis on default branch

error-prone-guidelines/src/main/java/tech/picnic/errorprone/guidelines/bugpatterns/BugPatternLink.java, error-prone-guidelines/src/test/java/tech/picnic/errorprone/guidelines/bugpatterns/BugPatternLinkTest.java, refaster-test-support/src/main/java/tech/picnic/errorprone/refaster/test/RefasterRuleCollection.java
Another branch I had laying around that I decided to polish.
```
Introduce `BugPatternLink` check (#1026)
This check validates that checks defined by Error Prone Support
reference the public website, unless they explicitly specify that their
diagnostics output must not include a link.
```
=> Introduce `BugPatternLink` check

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/InputStreamRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/InputStreamRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/InputStreamRulesTestOutput.java
:exclamation: This PR is on top of #603 :exclamation: 
```
Introduce `InputStream{Read,Skip}NBytes` Refaster rules (#993)
```
=> Introduce `InputStream{Read,Skip}NBytes` Refaster rules

error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/LexicographicalAnnotationAttributeListing.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/CollectionRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/CollectionRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/CollectionRulesTestOutput.java
Add the following expression to `CollectionIsEmpty`: `collection.stream().findAny().isEmpty()`.
Currently, this rule clashes with the rule `OptionalFirstCollectionElement`, which is matching `collection.stream().findAny()`, rewriting it to `collection.stream().findFirst()`. Not sure what's the best way to solve this issue, both use cases seem valid 🤔
1. Suppressing the suggestion to rewrite `collection.stream().findAny().isEmpty()` to `collection.stream().findFirst().isEmpty()` leads to a loop since `stream().findFirst().isEmpty()` is rewritten to `stream().findAny().isEmpty()`
This acts as a useful partner to `StreamIsEmpty`: expressions that match the one introduced in this PR can result as a consequence of applying the `StreamIsEmpty` rule: this allows for refactors like the following …
=> Extend `CollectionIsEmpty` Refaster rule

.renovaterc.json
Wanted to omit `dawidd6` to fit the PR description.
As suggested here: https://github.com/PicnicSupermarket/error-prone-support/pull/1039#issuecomment-1951878345.
=> Have Renovate file `action-download-artifact` PRs once every four weeks

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Based on an internal discussion, we found this case for a Refaster rule;
we can omit `.stream()` on a `Collection` and directly use `Flux.fromIterable`.
I wasn't sure about the order of rules and tests, so I placed them at the end, LMK if they need to move. :)
=> Introduce `FluxFromIterable` Refaster rule

error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/LexicographicalAnnotationAttributeListing.java
As part of https://github.com/checkstyle/checkstyle/issues/14137 I'm enabling the `LexicographicalAnnotationAttributeListing` check. I encountered a problem related to this: https://github.com/PicnicSupermarket/error-prone-support/blob/master/integration-tests/checkstyle-init.patch#L78. 
Therefore I'm filing this PR.
=> Exempt `picocli.CommandLine.Option#names` annotation attribute from reordering

pom.xml
```
Upgrade Error Prone fork v2.25.0-picnic-1 -> v2.25.0-picnic-2 (#1065)
See:
- https://github.com/PicnicSupermarket/error-prone/releases/tag/v2.25.0-picnic-2
- https://github.com/PicnicSupermarket/error-prone/compare/v2.25.0-picnic-1...v2.25.0-picnic-2
```
=> Upgrade Error Prone fork v2.25.0-picnic-1 -> v2.25.0-picnic-2

.github/workflows/build.yml, .github/workflows/codeql.yml, .github/workflows/deploy-website.yml, .github/workflows/openssf-scorecard.yml, .github/workflows/pitest-analyze-pr.yml, .github/workflows/pitest-update-pr.yml, .github/workflows/run-integration-tests.yml, .github/workflows/sonarcloud.yml
See [these steps](https://github.com/step-security/harden-runner?tab=readme-ov-file#github-hosted-runners) for context. I noticed this feature when checking the [Byte Buddy GHA setup](https://github.com/raphw/byte-buddy/blob/3b4ed21c97a960ddd8196cdd76c62810f9a6cfd2/.github/workflows/main.yml).
```
Introduce GitHub Actions `step-security/harden-runner` step (#1063)
```
=> Introduce GitHub Actions `step-security/harden-runner` step

.github/workflows/openssf-scorecard.yml
```
Have `step-security/harden-runner` audit the OpenSSF Scorecard update workflow (#1076)
When executed on `master` this workflow requires additional permissions;
let's find out what they are.
```
=> Have `step-security/harden-runner` audit the OpenSSF Scorecard update workflow

error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/Slf4jLogStatementTest.java
Randomly stumbled upon this while I was working on the upcoming blog.
=> Drop unused field in `Slf4jLogStatementTest`

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/CollectionRules.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/StreamRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StreamRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StreamRulesTestOutput.java
~:exclamation: This PR is on top of #1025. :exclamation:~
```
Compact and replace `StreamIs{,Not}Empty` Refaster rules (#1028)
The new `StreamFindAnyIs{Empty,Present}` rules are simpler thanks to the
use of `@AlsoNegation`. In some cases an additional application of the
`OptionalIsEmpty` rule will be required.
```
=> Compact and replace `StreamIs{,Not}Empty` Refaster rules

error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/OptionalOrElse.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/OptionalRules.java, error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/OptionalOrElseTest.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/OptionalRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/OptionalRulesTestOutput.java, integration-tests/checkstyle-expected-changes.patch, refaster-runner/src/main/java/tech/picnic/errorprone/refaster/runner/Refaster.java
I found a branch from back in 2021; decided to dust it off :)
```
Introduce `OptionalOrElse` check (#1024)
While there, extend the `OptionalIdentity` Refaster rule to
automatically resolve one class of `NestedOptionals` violations.
```
=> Introduce `OptionalOrElse` check

.github/release.yml
Discussed this offline with @Stephan202. 
When we have an update consideration or deprecation, it's usually quite important, so we want to have it at the top of the release notes. An example is the release notes from `v0.16.0`: https://github.com/PicnicSupermarket/error-prone-support/releases/tag/v0.16.0.
=> Start release notes with "Update considerations and deprecations" section

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ComparatorRules.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/EqualityRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ComparatorRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ComparatorRulesTestOutput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/EqualityRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/EqualityRulesTestOutput.java
```
Introduce Refaster rules that resolve `EnumOrdinal` violations (#1104)
```
These rules resolve some of the violations reported by the [EnumOrdinal](https://errorprone.info/bugpattern/EnumOrdinal) check new in Error Prone [2.26.0](https://github.com/google/error-prone/releases/tag/v2.26.0).
=> Introduce Refaster rules that resolve `EnumOrdinal` violations

pom.xml
```
Upgrade Error Prone fork v2.26.1-picnic-1 -> v2.26.1-picnic-2 (#1119)
See:
- https://github.com/PicnicSupermarket/error-prone/releases/tag/v2.26.1-picnic-2
- https://github.com/PicnicSupermarket/error-prone/compare/v2.26.1-picnic-1...v2.26.1-picnic-2
```
=> Upgrade Error Prone fork v2.26.1-picnic-1 -> v2.26.1-picnic-2

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Something I noticed while going over the internal code base.
```
Update `FluxTake` Refaster rule for Reactor 3.5.0+ (#1128)
```
=> Update `FluxTake` Refaster rule for Reactor 3.5.0+

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/OptionalRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/OptionalRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/OptionalRulesTestOutput.java
I spotted the following interesting piece of code:
```java
Optional.ofNullable(null)
```
which should obviously always be:
```java
Optional.empty()
```
---
```
Introduce `OptionalEmpty` Refaster rule (#1156)
```
=> Introduce `OptionalEmpty` Refaster rule

.github/workflows/build.yml, .github/workflows/codeql.yml, .github/workflows/pitest-analyze-pr.yml, .github/workflows/pitest-update-pr.yml, .github/workflows/run-integration-tests.yml, .github/workflows/sonarcloud.yml
```
Update `step-security/harden-runner` configuration (#1177)
This resolves recent build failures by ensuring that JDKs can be
downloaded.
```
=> Update `step-security/harden-runner` configuration

.renovaterc.json
This automated PR simplifies the matchers in the package rules by migrating to `packageName` matchers as opposed to `depName` matchers. It furthermore may remove some human-readable strings to match on as this is obsolete with the new `packageName` matchers.
=> PSM-2580 Simplify Renovate matchers

.github/workflows/openssf-scorecard.yml
```
Allow OpenSSF Scorecard analysis to access `api.scorecard.dev` (#1193)
```
=> Allow OpenSSF Scorecard analysis to access `api.scorecard.dev`

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
As discussed during PR review with @werli.
```
Extend `FluxConcatMap` Refaster rule (#1213)
```
=> Extend `FluxConcatMap` Refaster rule

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/EqualityRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/EqualityRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/EqualityRulesTestOutput.java
```
Introduce `EnumReferenceEqualityLambda` Refaster rule (#1239)
```
=> Introduce `EnumReferenceEqualityLambda` Refaster rule

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/EqualityRules.java
```
Suppress new SonarCloud  (#1248)
```
This should have been part of #1239. (When I checked the SonarCloud report the PR was already merged.)
=> Suppress new SonarCloud warning

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Futures subscribe eagerly. This means that `Mono#fromFuture(CompletableFuture)` already executes the contents of the future on assembly time (even when that `Future` is constructed from a `Mono` as we do in our reactive Caffeine caches).
I therefore suggest instead to always use `Mono#fromFuture(Supplier)`, which will only instantiate (and thus execute) the future on subscription, i.e. much closer to how we usually do everything 😄
=> Introduce `MonoFromFutureSupplier{,Boolean}` Refaster rules

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
This PR adds another case for the `FluxJust` rule, which replaces the following pattern
```java
Mono.just(value).repeat().take(1);
```
with
```java
Flux.just(value);
```
```
Extend `FluxJust` Refaster rule (#1253)
```
=> Extend `FluxJust` Refaster rule

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/CollectionRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/CollectionRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/CollectionRulesTestOutput.java
I think this is a candidate for "combinations of operators that don't make sense".
I tried to extend the rule with rules like 
```
static final class SetStreamFilter<T> {
@BeforeTemplate
Stream<?> before(Set<T> set, Predicate<T> predicate) {
return set.stream().filter(predicate).distinct();
}
@AfterTemplate
Stream<?> after(Set<T> set, Predicate<T> predicate) {
return set.stream().filter(predicate);
}
}
```
But the number of permutations of different operators before using `#distinct` is a lot.
```
Rely on Set's property to preserve distinct elements when streaming
```
=> Introduce `SetStream` Refaster rule

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/FileRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/FileRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/FileRulesTestOutput.java
```
Introduce `FilesCreateTempFileToFile` Refaster rule (#1162)
```
Inspired by apache/maven-install-plugin#47, found through #1159.
=> Introduce `FilesCreateTempFileToFile` Refaster rule

integration-tests/checkstyle.sh, integration-tests/run-integration-test.sh
This PR aims to split out some of the changes from #894 to minimize the diff of that PR.
It's introducing too many changes to review at once. After we merged this PR, it'll be easier to review the other.
Credits to @oxkitsune for these changes!
=> Introduce generic `run-integration-test.sh` script

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ClassRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ClassRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ClassRulesTestOutput.java
* Perhaps opinionated, but personally, I find the `Class.class:cast` alternative more readable, especially when working with _Streams_.
* One downside to this rule, is that we lose the compile-time cast checks in exchange for runtime checks.
What are your guys thoughts?
```
Introduce `Class(Reference|Literal)Cast` class rules
```
=> Introduce `Class{Literal,Reference}Cast` Refaster rules

documentation-support/src/main/java/tech/picnic/errorprone/documentation/DocumentationGeneratorTaskListener.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/IdentityConversion.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/FileRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/FileRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/FileRulesTestOutput.java
```
Introduce additional `File` and `Path` Refaster rules (#1282)
```
=> Introduce additional `File` and `Path` Refaster rules

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ComparatorRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ComparatorRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ComparatorRulesTestOutput.java
```
Introduce `{Max,Min}Of{Array,Collection}` Refaster rules (#1276)
While there, generalize the `{Max,Min}OfVarargs` rules.
```
=> Introduce `{Max,Min}Of{Array,Collection}` Refaster rules

error-prone-contrib/pom.xml, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java, pom.xml
```
Introduce `MonoFromFutureAsyncLoadingCacheGet` Refaster rule (#1290)
```
=> Introduce `MonoFromFutureAsyncLoadingCacheGet` Refaster rule

documentation-support/pom.xml, documentation-support/src/main/java/tech/picnic/errorprone/documentation/BugPatternTestExtractor.java, documentation-support/src/main/java/tech/picnic/errorprone/documentation/RefasterRuleCollectionTestExtractor.java, documentation-support/src/test/java/tech/picnic/errorprone/documentation/BugPatternTestExtractorTest.java, documentation-support/src/test/java/tech/picnic/errorprone/documentation/RefasterRuleCollectionTestExtractorTest.java, error-prone-contrib/pom.xml, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ImmutableMultisetRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ImmutableMultisetRulesTestOutput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ImmutableSortedMultisetRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ImmutableSortedMultisetRulesTestOutput.java, refaster-test-support/src/main/java/tech/picnic/errorprone/refaster/test/RefasterRuleCollection.java
```
Introduce `RefasterRuleTestExtractor` for documentation generation (#1317)
This new `Extractor` implementation collects Refaster example input and 
output code from rule collection tests.
This change also introduces explicit compilation steps for the test
code. As a side-effect this produces faster feedback in case of invalid
input or output code.
```
After this PR, approximately one more PR remains to port the remainder of the logic on the `website` branch to `master`. After that we can configure the build such that any change on `master` is nearly immediately reflected on https://error-prone.picnic.tech.
(The build will fail because of [this issue](https://github.com/PicnicSupermarket/error-prone-support/pull/1069#issuecomment-2322956932); will try to …
=> Introduce `RefasterRuleTestExtractor` for documentation generation

error-prone-contrib/pom.xml
```
Use `rewrite-java-17` rather than `rewrite-java-11` (#1330)
```
See [this comment](https://github.com/PicnicSupermarket/error-prone-support/pull/1329#issuecomment-2350934389).
=> Use `rewrite-java-17` rather than `rewrite-java-11`

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/StringRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StringRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StringRulesTestOutput.java
```
Introduce Refaster rules for Sonar's java:S4635 rule (#1320)
As well as two related expressions that can be optimized.
See:
- https://sonarcloud.io/organizations/picnic-technologies/rules?open=java%3AS4635&rule_key=java%3AS4635
- https://github.com/SonarSource/sonar-java/blob/26157927314eed0105449e8c7bc7e86c34148a83/java-checks/src/main/java/org/sonar/java/checks/StringOffsetMethodsCheck.java
```
=> Introduce Refaster rules for Sonar's java:S4635 rule

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/CollectionRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/CollectionRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/CollectionRulesTestOutput.java
```
Introduce `CollectionIterator` Refaster rule (#1347)
This rule supersedes the more specific `ImmutableCollectionIterator` rule.
```
=> Extend `ImmutableCollectionIterator` refaster rule

documentation-support/src/test/java/tech/picnic/errorprone/documentation/DocumentationGeneratorTaskListenerTest.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/JUnitClassModifiers.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssortedRules.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ImmutableEnumSetRules.java, error-prone-contrib/src/test/java/tech/picnic/errorprone/refasterrules/RefasterRulesTest.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssortedRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssortedRulesTestOutput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ImmutableEnumSetRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ImmutableEnumSetRulesTestOutput.java
```
Introduce `ImmutableEnumSetRules` refaster rules
```
=> Introduce `ImmutableEnumSetRules` Refaster rule collection

error-prone-contrib/pom.xml, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/MicrometerRules.java, error-prone-contrib/src/test/java/tech/picnic/errorprone/refasterrules/RefasterRulesTest.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/MicrometerRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/MicrometerRulesTestOutput.java, pom.xml
```
Introduce `MicrometerRules` Refaster rule collection (#1365)
```
=> Introduce `MicrometerRules` Refaster rule collection

error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/ConstantNaming.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/BugCheckerRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/BugCheckerRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/BugCheckerRulesTestOutput.java
As also flagged [here](https://github.com/PicnicSupermarket/error-prone-support/pull/783#discussion_r1502274717) and [here](https://github.com/PicnicSupermarket/error-prone-support/pull/794#discussion_r1818105009).
```
Introduce `NameContentEquals` Refaster rule (#1379)
```
=> Introduce `NameContentEquals` Refaster rule

error-prone-contrib/pom.xml
This change resolves an issue caused by #1283, and flagged by @pzygielo [here](https://github.com/PicnicSupermarket/error-prone-support/pull/1283#issuecomment-2451777445). Thanks Piotrek!
(The bug didn't manifest while testing the release, as in all relevant contexts we also have `refaster-runner` on the annotation processor classpath, and that module has a _runtime_ dependency on `refaster-support`.)
```
Fix `error-prone-contrib` runtime classpath (#1387)
```
We should cut a new release with this fix.
=> Fix `error-prone-contrib` runtime classpath

.github/workflows/deploy-website.yml
This upgrade unblocks #1391. Opening the PR manually because Renovate currently can't open GitHub Actions upgrade PRs. Flagged that internally.
```
Upgrade ruby/setup-ruby v1.174.0 -> v1.199.0 (#1392)
See:
- https://github.com/ruby/setup-ruby/releases/tag/v1.175.0
- https://github.com/ruby/setup-ruby/releases/tag/v1.176.0
- https://github.com/ruby/setup-ruby/releases/tag/v1.177.0
- https://github.com/ruby/setup-ruby/releases/tag/v1.178.0
- https://github.com/ruby/setup-ruby/releases/tag/v1.179.0
- https://github.com/ruby/setup-ruby/releases/tag/v1.180.0
- https://github.com/ruby/setup-ruby/releases/tag/v1.181.0
- https://github.com/ruby/setup-ruby/releases/tag/v1.182.0
- https://github.com/ruby/setup-ruby/releases/tag/v1.183.0
- …
```
=> Upgrade ruby/setup-ruby v1.174.0 -> v1.199.0

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/OptionalRules.java
```
Track `StreamFlatMapOptional` Refaster rule caveat (#1410)
```
(I often track notes like these locally, but perhaps making it explicit here motivates me to finalize a [JMH benchmark generation doodle](https://github.com/PicnicSupermarket/error-prone-support/compare/master...sschroevers/reactor-optimizations) I started on long aog.)
=> Track `StreamFlatMapOptional` Refaster rule caveat

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
This PR introduces a bunch of rules associated to `StepVerifier.Asserations` and a trivial `StepVerifier` rule.
---
I spotted the following interesting pattern:
```java
Mono.empty()
.as(StepVerifier::create)
.expectError(SpecificException.class)
.verifyThenAssertThat()
.hasOperatorErrorWithMessage("msg");
```
Which made me find the interesting `StepVerifier#Assertions` API. It's quite low-level, and IMO not as straightforward to read and write.
The example itself is most often represented in our code-base using AssertJ's richer API:
```java
Mono.empty()
.as(StepVerifier::create)
.verifyErrorSatisfies(t ->
assertThat(t)
.isInstanceOf(SpecificException.class)
.hasMessage("msg"));
```
---
```
Introduce assorted Reactor `StepVerifier` Refaster rules (#1132)
```
=> Introduce assorted Reactor `StepVerifier` Refaster rules

.github/workflows/build.yml, .github/workflows/run-integration-tests.yml, pom.xml
```
Replace deprecated `build-helper:remove-project-artifact` goal (#1413)
```
This resolves the following warning:
```
[WARNING]  Goal 'remove-project-artifact' is deprecated: There is a similar goal: dependency:purge-local-repository <https://maven.apache.org/plugins/maven-dependency-plugin/purge-local-repository-mojo.html> By the way such goal should by not used with Maven 3/4 anymore.
```
(As for whether such a goal should not be used at all: (a) there's no point in caching these artifacts, and (b) we know from internal projects that keeping such SNAPSHOTs around can hide project cycles. Not likely to happen with our simple Maven build setup, but still.)
Tested as follows:
```sh
$ mvn clean install -DskipTests -Dverification.skip
$ find …
```
=> Replace deprecated `build-helper:remove-project-artifact` goal

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/FileRules.java, integration-tests/checkstyle-expected-changes.patch, integration-tests/checkstyle-init.patch, integration-tests/checkstyle.sh, integration-tests/run-integration-test.sh
```
Update Checkstyle integration test (#1424)
- Move Checkstyle-specific build parameters out of
`run-integration-test.sh`.
- Build with `-Dmaven.compiler.failOnError=true` to compensate for
`<failOnError>false</failOnError>` configured by the enabled Maven
profiles.
- Tweak `XdocGenerator.java` logic prior to integration test execution,
to work around a subtle semantic difference introduced by the
`FilesCreateTempFileToFile` Refaster rule.
- Document this difference on the relevant Refaster rules.
- To aid debugging, run Maven commands with `set -x`, such that the
exact command executed is logged.
- Update the patch file containing the expected changes.
```
=> Update Checkstyle integration test

error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/RedundantStringEscape.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/Slf4jLogStatement.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/StringJoin.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/BugCheckerRules.java, error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/RedundantStringEscapeTest.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/BugCheckerRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/BugCheckerRulesTestOutput.java, error-prone-guidelines/src/main/java/tech/picnic/errorprone/guidelines/bugpatterns/BugPatternLink.java, error-prone-guidelines/src/main/java/tech/picnic/errorprone/guidelines/bugpatterns/ErrorProneRuntimeClasspath.java, error-prone-guidelines/src/main/java/tech/picnic/errorprone/guidelines/bugpatterns/ExhaustiveRefasterTypeMigration.java, error-prone-utils/src/main/java/tech/picnic/errorprone/utils/SourceCode.java, error-prone-utils/src/test/java/tech/picnic/errorprone/utils/SourceCodeTest.java
```
Introduce `RedundantStringEscape` check (#1138)
This check aims to simplify string constants by dropping redundant
single quote escape sequences. The check is optimized for performance.
While there, update existing checks such that they do not introduce
violations of the type flagged by this new check.
```
=> Introduce `RedundantStringEscape` check

error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/Slf4jLoggerDeclaration.java, error-prone-contrib/src/test/java/tech/picnic/errorprone/bugpatterns/Slf4jLoggerDeclarationTest.java
```
Fix `Slf4jLoggerDeclaration` flag name (#1436)
```
=> Fix `Slf4jLoggerDeclaration` flag name

README.md, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Another set of trivial Reactor Refaster rules.
```
Introduce `PublisherProbeAssertWas{,Not}{Subscribed,Cancelled,Requested}` Refaster rules (#1423)
While there, fix a typo in `README.md`.
```
=> Introduce `PublisherProbeAssertWas{,Not}{Subscribed,Cancelled,Requested}` Refaster rules

integration-tests/checkstyle-init.patch, integration-tests/metrics-init.patch
Fixes [this](https://github.com/PicnicSupermarket/error-prone-support/pull/985#issuecomment-2536960426) issue.
```
Make integration tests Error Prone 2.36.0-compatible (#1455)
```
=> Make integration tests Error Prone 2.36.0-compatible

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssertJThrowingCallableRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJThrowingCallableRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJThrowingCallableRulesTestOutput.java
This PR aims to get rid of the following part of the `init-patch` of the new IT: https://github.com/PicnicSupermarket/error-prone-support/pull/1468/files#diff-6b99a1fb957cc4c8081a8a95423c965335a67c526f4b5b634aafa0d6912dc4dcR61. 
Not sure about the * part in the title, let me know what options are :D.
=> Introduce `AssertThatThrownBy*ExceptionRootCauseHasMessage` Refaster rules

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/StreamRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StreamRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StreamRulesTestOutput.java
Prefer
```java
stream.map(map::get).filter(Objects::nonNull)
``` 
over
```java
stream.filter(map::containsKey).map(map::get)
```
```
Introduce `StreamMapFilter` Refaster rule (#1467)
```
=> Introduce `StreamMapFilter` Refaster rule

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssertJThrowingCallableRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJThrowingCallableRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJThrowingCallableRulesTestOutput.java
```
Generalize `AssertThatThrownBy` Refaster rule (#1477)
By replacing it with the `AssertThatThrownByAsInstanceOfThrowable` and
`AssertThatThrownByIsInstanceOf` rules that are slightly more type-safe.
```
This resolves an issue discussed [here](https://github.com/PicnicSupermarket/error-prone-support/pull/1468#discussion_r1894610018).
=> Generalize `AssertThatThrownBy` Refaster rule

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssertJRules.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssertJStringRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJStringRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJStringRulesTestOutput.java
```
Introduce `AssertThatString{Contains,DoesNotContain}` Refaster rules (#1479)
While there, extend `AssertThatIterableIsEmpty`.
```
=> Introduce `AssertThatString{Contains,DoesNotContain}` Refaster rules

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/CharSequenceRules.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/StringRules.java, error-prone-contrib/src/test/java/tech/picnic/errorprone/refasterrules/RefasterRulesTest.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/CharSequenceRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/CharSequenceRulesTestOutput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StringRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/StringRulesTestOutput.java
This aims to solve the following issue: https://github.com/PicnicSupermarket/error-prone-support/issues/1394. 
@timtebeek mentioned that OpenRewrite has some checks that ensure that only the correct recipes are loaded for the Java version it's running on. For us I also don't see any problems for running on our code. The only advantage is that we will be matching more now :).
=> Introduce `CharSequenceRules` Refaster rule collection

integration-tests/metrics-expected-changes.patch
```
Sync Dropwizard Metrics integration test (#1482)
```
Show have been part of #1479.
=> Sync Dropwizard Metrics integration test

.github/workflows/build.yml
```
Run GitHub Actions workflows on `macos-15` and `windows-2025` (#1490)
See:
- https://github.com/actions/runner-images/blob/main/README.md#available-images
- https://github.com/actions/runner-images/blob/main/images/macos/macos-15-Readme.md
- https://github.com/actions/runner-images/blob/main/images/windows/Windows2025-Readme.md
```
These new images are still in beta. Let's see whether they work for us :eyes:
=> Run GitHub Actions workflows on `macos-15` and `windows-2025`

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/NullRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/NullRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/NullRulesTestOutput.java
Pretty trivial extension after I saw this construct in the wild.
---
```
Extend `{Is,Non}NullFunction` Refaster rules (#1494)
```
=> Extend `{Is,Non}NullFunction` Refaster rules

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssertJCharSequenceRules.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssertJMapRules.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssertJRules.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssertJStringRules.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssortedRules.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/CollectionRules.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ImmutableMapRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJCharSequenceRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJCharSequenceRulesTestOutput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJStringRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJStringRulesTestOutput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/CollectionRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/CollectionRulesTestOutput.java
```
Generalize assorted Refaster rules (#1481)
```
This was done manually, with the help of IntelliJ IDEA's "Parameter type may be weakened" inspection. I considered writing an Error Prone check for this, but that'd be quite involved, requiring more effort than I'm willing to spend at this time.
=> Generalize assorted Refaster rules

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/TestNGToAssertJRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/TestNGToAssertJRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/TestNGToAssertJRulesTestOutput.java
```
Extend `TestNGToAssertJRules` Refaster rule collection (#1483)
By migrating all remaining `assertEquals` methods.
```
While working on this I found an issue; filed testng-team/testng#3199.
(Perhaps it's time to move this to an Error Prone check, but given that we don't use TestNG internally anymore, that's likely not worth the trouble. I opened this PR primarily because I had a branch with some of these changes, and decided it was time to "flush" that work.)
=> Extend `TestNGToAssertJRules` Refaster rule collection

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
I want to advocate for using `Flux#mapNotNull` more, even if that includes defaulting to an explicit `null` value.
I'm happy to learn how to fuse those into one rule. :eyes:
```
Introduce `FluxMapNotNull{,Transformation}OrElse` Refaster rules (#1493)
```
=> Introduce `FluxMapNotNull{,Transformation}OrElse` Refaster rules

error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/ExplicitArgumentEnumeration.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/NonStaticImport.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ImmutableTableRules.java, error-prone-contrib/src/test/java/tech/picnic/errorprone/refasterrules/RefasterRulesTest.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ImmutableTableRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ImmutableTableRulesTestOutput.java
```
Introduce `ImmutableTableRules` Refaster rule collection (#1489)
```
This work results from #1223 and [this comment](https://github.com/PicnicSupermarket/error-prone-support/pull/1488#discussion_r1899183057), with the observation that `ImmutableTable` has a distinct builder type. The rules introduced here are a subset of those defined by `ImmutableMapRules`.
=> Introduce `ImmutableTableRules` Refaster rule collection

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/JUnitToAssertJRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/JUnitToAssertJRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/JUnitToAssertJRulesTestOutput.java
```
Extend `JUnitToAssertJRules` Refaster rule collection (#1484)
By migrating all remaining `assertArrayEquals` methods.
```
Analogous to #1483, this is me putting up a PR for a existing branch, this time after extending the work with the help of GitHub Copilot. (Also here, perhaps an Error Prone check is in order, but not today.)
=> Extend `JUnitToAssertJRules` Refaster rule collection

README.md, pom.xml
```
Make Mockito setup IntelliJ IDEA-compatible (#1500)
See https://github.com/mockito/mockito/issues/3037#issuecomment-2569680756
```
Hat tip to @runeflobakk for [this clearly-written comment](https://github.com/mockito/mockito/issues/3037#issuecomment-2569680756).
=> Make Mockito setup IntelliJ IDEA-compatible

.github/workflows/build.yml, .github/workflows/deploy-website.yml, README.md, documentation-support/pom.xml, error-prone-contrib/pom.xml, error-prone-experimental/pom.xml, error-prone-guidelines/pom.xml, error-prone-utils/pom.xml, pom.xml, refaster-compiler/pom.xml, refaster-runner/pom.xml, refaster-support/pom.xml, refaster-test-support/pom.xml, settings.xml, website/generate-version-compatibility-overview.sh
```
Upgrade Error Prone fork 2.36.0-picnic-1 -> 2.36.0-picnic-2 (#1499)
This new release is published using GitHub Packages rather than
JitPack. This comes with a simpler release setup and a (hopefully) more
stable package repository. A minor downside is that GitHub Packages
require authenticated access, even for read access. The documentation
has been updated accordingly.
The new release is no longer published using a custom groupId, enabling
some build simplifications.
While there, some obsolete fork-related documentation and configuration
is dropped.
See:
- https://github.com/PicnicSupermarket/error-prone/releases/tag/v2.36.0-picnic-2
- https://github.com/PicnicSupermarket/error-prone/compare/v2.36.0-picnic-1...v2.36.0-picnic-2
```
This is possible thanks to …
=> Upgrade Error Prone fork 2.36.0-picnic-1 -> 2.36.0-picnic-2

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssertJEnumerableRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJEnumerableRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJEnumerableRulesTestOutput.java
```
Extend size-related `AssertJEnumerableRules` Refaster rules (#1512)
By also matching expressions ending in `.returnToIterable()`.
```
=> Extend size-related `AssertJEnumerableRules` Refaster rules

.github/workflows/run-integration-tests.yml
```
Fix integration test `step-security/harden-runner` configuration (#1541)
Resolves #1534.
```
=> Fix integration test `step-security/harden-runner` configuration

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
```
Introduce `MonoFromFutureAsyncLoadingCacheGetAll` Refaster rule (#1551)
```
=> Introduce `MonoFromFutureAsyncLoadingCacheGetAll` Refaster rule

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/OptionalRules.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/PrimitiveRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/PrimitiveRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/PrimitiveRulesTestOutput.java
Inspired by google/guava#7636.
```
Introduce `ArraysCompareUnsigned{Byte,Int,Long}s` Refaster rules (#1542)
While there, document possible `StreamFlatMapOptional` improvement.
```
=> Introduce `ArraysCompareUnsigned{Byte,Int,Long}s` Refaster rules

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
* `Mono#when` aggregates multiple publishers into one `Mono<Void>`, passing only one publisher to the argument is redundant and can be re-fastered into a `Mono#then`. 
```
Extend `MonoThen` Refaster rule (#1556)
```
=> Extend `MonoThen` Refaster rule

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/ReactorRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/ReactorRulesTestOutput.java
Another bite-sized Refaster rule extension.
```
Extend `MonoSingleOptional` Refaster rule (#1553)
```
=> Extend `MonoSingleOptional` Refaster rule

pom.xml
```
Upgrade Error Prone fork 2.36.0-picnic-2 -> 2.36.0-picnic-4 (#1591)
See:
- https://github.com/PicnicSupermarket/error-prone/releases/tag/v2.36.0-picnic-3
- https://github.com/PicnicSupermarket/error-prone/releases/tag/v2.36.0-picnic-4
- https://github.com/PicnicSupermarket/error-prone/compare/v2.36.0-picnic-2...v2.36.0-picnic-4
```
=> Upgrade Error Prone fork 2.36.0-picnic-2 -> 2.36.0-picnic-4

pom.xml
```
Upgrade Arcmutate plugins (#1586)
These upgrades were not picked up automatically due to a groupId change.
- Upgrade Pitest Git plugins 1.1.4 -> 2.1.0
- Upgrade Arcmutate 1.2.2 -> 1.3.2
- Upgrade pitest-accelerator-junit5 1.0.6 -> 1.2.0
```
Hat tip to @jqno for his instructions [here](https://github.com/jqno/equalsverifier/pull/1055#issuecomment-2720240606). Based on _local_ testing I shouldn't rename the license file, but let's see what GitHub Actions thinks :eyes:
(Tested before and after results: no changes except that on [this line](https://github.com/PicnicSupermarket/error-prone-support/blob/7a051146b618a206baa0761c2fdb1878574ec77d/error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/RedundantStringConversion.java#L305 …
=> Upgrade Arcmutate plugins

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/FileRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/FileRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/FileRulesTestOutput.java
Proposing a quick rule for something that's come up repeatedly on our end. Figured it'd be a good match for a Refaster rule.
The goal here is to avoid concurreny issues when two processes are simultaneously checking if a directory exists, before attempting to create that directory, as part of a single check. By flipping around these two commands you avoid conflicts.
I didn't spot any existing tests for any `FileRule`; let me know if I missed any. If so I'd propose to also verify the negation of `!Files.exists(path) && !path.toFile().mkdirs()`.
- As discovered on https://github.com/openrewrite/rewrite/pull/5189
=> Introduce two `FileRules` Refaster rules

.github/workflows/build.yml, .github/workflows/deploy-website.yml, pom.xml, run-full-build.sh, settings.xml
```
Drop unmaintained `reactor-error-prone` dependency (#1650)
This dependency is incompatible with Error Prone 2.38.0. By dropping it, 
the `non-maven-central` Maven profile and Jitpack mirror can also be
dropped.
```
=> Drop unmaintained `reactor-error-prone` dependency

error-prone-contrib/src/main/java/tech/picnic/errorprone/bugpatterns/IdentityConversion.java, pom.xml
Renovate didn't open a PR, so did it manually.
```
Upgrade Error Prone 2.37.0 -> 2.38.0 (#1649)
Resolves #1646.
See:
- https://github.com/google/error-prone/releases/tag/v2.38.0
- https://github.com/google/error-prone/compare/v2.37.0...v2.38.0
- https://github.com/PicnicSupermarket/error-prone/compare/v2.37.0-picnic-1...v2.38.0-picnic-1
```
=> Upgrade Error Prone 2.37.0 -> 2.38.0

error-prone-contrib/pom.xml, error-prone-guidelines/pom.xml, pom.xml, refaster-runner/pom.xml, refaster-test-support/pom.xml
```
Drop IDEA-342187 workaround (#1648)
As of IntelliJ IDEA 2024.3.2.2, the IDE gracefully handles the absence
of explicitly specified annotation processor path dependency versions,
consistent with `maven-compiler-plugin`'s dependency resolution.
```
=> Drop IDEA-342187 workaround

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/TestNGToAssertJRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/TestNGToAssertJRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/TestNGToAssertJRulesTestOutput.java
**Summary**
Refactor a few Refaster recipes by moving type variable declarations from the method level to the class level. This ensures consistency between before() and after() templates.
**Motivation**
OpenRewrite doesn’t support method-level generic type variables, which can result in incorrect or uncompilable replacements.
=> Share same generic parameters with the templates

.github/workflows/error-prone-compat.yml, .github/workflows/sonarcloud.yml, run-full-build.sh
See discussion in #1646. I opted not to bother with testing against a "locally" built HEAD release of Error Prone, as that would at most speed up incompatibility identification by 24 hours, while potentially causing weeks/months of build failures between the time an incompatibility is introduced and a subsequent release.
```
Validate compatibility with latest Error Prone release (#1651)
Every day and after each merged change we now run a GitHub Actions
workflow that builds the project against the latest Error Prone release,
as determined by Maven. This should pro-actively inform us of
incompatibilities that demand a new release.
While there:
- Drop a redundant permission declaration from the SonarCloud workflow.
- Update `run-full-build.sh` to parallelize the …
```
=> Validate compatibility with latest Error Prone release

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssertJMapRules.java, error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssertJRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJMapRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJMapRulesTestOutput.java
While working on https://github.com/openrewrite/rewrite-testing-frameworks/pull/713 I discovered some patterns that weren't included as rules here, and figured you all would appreciate having these as well.
=> Extend `AssertJMapRules` Refaster rule collection

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssertJThrowingCallableRules.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJThrowingCallableRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJThrowingCallableRulesTestOutput.java
- Following https://github.com/assertj/assertj/issues/3715
@rickie would this be an accepted contribution if tests are added?
=> Introduce `AbstractThrowableAssertHasCauseReference` Refaster rule

error-prone-contrib/src/main/java/tech/picnic/errorprone/refasterrules/AssertJDurationRules.java, error-prone-contrib/src/test/java/tech/picnic/errorprone/refasterrules/RefasterRulesTest.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJDurationRulesTestInput.java, error-prone-contrib/src/test/resources/tech/picnic/errorprone/refasterrules/AssertJDurationRulesTestOutput.java
Figured this would fit in nicely with the other AssertJ rules for more expressive assertions.
=> Introduce `AssertJDurationRules` Refaster rule collection

integration-tests/run-integration-test.sh
```
Fix integration tests (#1821)
By explicitly controlling the `MAVEN_ARGS` environment variable, the 
integration test scripts become compatible with the GitHub Actions
changes introduced in c70e0e76f6ef2602714dd0943a73bfce000c5927.
```
=> Fix integration tests

.github/workflows/build.yml, .github/workflows/integration-tests.yml, .github/workflows/pitest-analyze-pr.yml, .github/workflows/pitest-update-pr.yml, pom.xml, settings.xml
```
Deploy SNAPSHOTs to the Maven Central snapshot repository (#1784)
Successful builds on the default branch are now followed by a `mvn
deploy` step that signs and uploads the produced SNAPSHOT artifacts. 
While there:
- Remove some unnecessary quotes from GitHub Actions workflow files.
- Move a comment about an Error Prone flag to its proper location.
```
=> Deploy SNAPSHOTs to the Maven Central snapshot repository

documentation-support/src/main/java/tech/picnic/errorprone/documentation/DocumentationGeneratorTaskListener.java, documentation-support/src/test/java/tech/picnic/errorprone/documentation/Compilation.java, documentation-support/src/test/java/tech/picnic/errorprone/documentation/DocumentationGeneratorTaskListenerTest.java
This is quite an important quality of life improvement. It avoids confusing users and AI coding agents when e.g. a non-existent method is referenced.
```
Skip documentation generation on compilation error (#1826)
This change prevents `DocumentationGeneratorTaskListener` from analyzing
invalid code, as that may trigger an exception that prevents the 
original compilation error from properly being reported.
While there, improve `null` handing and test coverage.
```
=> Skip documentation generation on compilation error
